project:
  type: website
  output-dir: docs

website:
  title: "physics2-notes"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Electric Fields"
        href: electric-fields.qmd
      - text: "Resistor Circuits"
        href: rc-circuits.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

